name: Build SandboxSpy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Get dependencies
      run: |
        go get github.com/mitchellh/go-ps
        go mod tidy

    - name: Build Windows 64-bit
      run: GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -H=windowsgui" -gcflags=-trimpath=$GITHUB_WORKSPACE -asmflags=-trimpath=$GITHUB_WORKSPACE -o SandboxSpy_amd64.exe SandboxSpy.go

    - name: Build Windows 32-bit
      run: GOOS=windows GOARCH=386 go build -ldflags="-s -w -H=windowsgui" -gcflags=-trimpath=$GITHUB_WORKSPACE -asmflags=-trimpath=$GITHUB_WORKSPACE -o SandboxSpy_386.exe SandboxSpy.go

    - name: Build decoder
      run: go build -o decoder decoder.go

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SandboxSpy-binaries
        path: |
          SandboxSpy_amd64.exe
          SandboxSpy_386.exe
          decoder
